# Generated by Django 2.1 on 2020-04-24 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apparels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='log_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
