# Generated by Django 3.0.5 on 2020-04-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apparels', '0002_apparel_log_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stock', models.IntegerField(max_length=10)),
                ('orders', models.IntegerField(max_length=10)),
                ('apparel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apparels.Apparel')),
            ],
        ),
    ]
